version: '3.3'

services:
    postgres:
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: my-store
            POSTGRES_USER: ostricnano
            POSTGRES_PASSWORD: root
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ostricmariano@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
    mysql:
        image: mysql:5
        environment:
            - MYSQL_DATABASE=my-store
            - MYSQL_USER=
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PORT=3307
        ports:
            - "3307:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - PMA_HOST=mysql
      ports:
        - 8080:80



